### ISSUE TITLE
Support for PHP 7.4

### ISSUE THREAD

**Issue by binarious** [Behat/Transliterator#25]
This library should be updated to support PHP 7.4:

PHP Deprecated:  Array and string offset access syntax with curly braces is deprecated in [src/Behat/Transliterator/Transliterator.php on line 357](https://github.com/Behat/Transliterator/blob/9eb1092ed2a3eb06d3c51f79f208fe8ac1cac553/src/Behat/Transliterator/Transliterator.php#L357).

**Comment by kdambekalns** [comment]
PR #29 fixes this, btw…

**Comment by kdambekalns** [comment]
Could this please be resolved? The change is ready, PHP 7.4 is stable and with a project as widely used as this one, a certain "urgency" can be seen. Please? @stof or @everzet or @vearutop maybe?

**Comment by kdambekalns** [comment]
Hooray to #29 being merged, any reason not to release a new version now?

**Comment by kdambekalns** [comment]
Maybe @everzet could take care? 🙏

**Comment by kdambekalns** [comment]
Is there anything we can do to speed things up? /cc @everzet @stof

**Comment by Bukashk0zzz** [comment]
Please make a release of this package. 
Here 🦄 for more attention.

Now in all projects test logs look like this:
<img width="1406" alt="Screenshot 2019-12-19 at 09 43 27" src="https://user-images.githubusercontent.com/1908342/71154404-214c7200-2244-11ea-9ad8-cabb8a6a7181.png">

**Comment by kdambekalns** [comment]
Meanwhile a "solution" usign `symfony/strings` has been pointed out in https://github.com/Behat/Transliterator/pull/29#issuecomment-567699708

**Comment by kdambekalns** [comment]
This is getting less funny by the day.

- A lot of libraries (95 says Packagist) out there depend on this package, among them well-known players like (ahem) `behat/behat` and `gedmo/doctrine-extensions`.
- PHP 7.4 has meanwhile seen it's first patch-level release.
- Compatibility is ensured with #29, which has been merged 10 days ago.
- Multiple people asked for this to get some attention and/or asked how they could help.
- First projects switched to `symfony/strings` instead of this one, even though it still is "experimental"

All that is needed to fix this mess would be **a new release, something that takes three clicks** (counting from https://github.com/Behat/Transliterator) and a tiny bit of typing.

**Please. Help. The. PHP. Community!**

**Comment by kdambekalns** [comment]
Happy New Year! 🚀🎉🍾

Now that it's 2020, can we please have a new release?

**Comment by snapshotpl** [comment]
@stof @everzet Can you just release fixed version?

**Comment by PurHur** [comment]
Please consider whether you don't want to add new maintainers to this and other important behat packages.

**Comment by kdambekalns** [comment]
This is really looking like a dead project by now…

**Comment by desmax** [comment]
yay, it got a release! but why can't I still see it on packagist?

**Comment by kdambekalns** [comment]
Why is that support called "preliminary" in the release notes? Well, anyway. Thanks!

**Comment by stof** [comment]
CI is green on PHP 7.4 so I'm closing this issue.
